name: tests for web App

on: [pull_request]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies (including pytest)
        run: |
          pipenv install --dev

      - name: Run tests with Pytest
        working-directory: web-app
        run:
          pipenv install pytest && pipenv install && pipenv run python -m pytest

